POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Kummelin kultakuume keskustelupiiri",
  "author": "Jönssi",
  "url": "www.paskaksdgankuru.fi",
  "likes": 533,
  "user": "675b0504f6d4290a1dbc52fb"
}