POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Pehmeän linjan helmenkalastajat",
  "author": "Kai Helmenanastaja",
  "url": "www.helmetsarebelongtous.com",
  "likes": 13
}